### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by ccsspro** [harsathAI/Cryptocurrency-predicting-RNN-Model---Deep-Learning#1]
Got this error while executing
Traceback (most recent call last):
  File "C:\Users\CORDIACE\Miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-USD_close'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CORDIACE\Cryptocurrency\Cryptocurrency-predicting.py", line 101, in <module>
    checker_function()
  File "C:\Users\CORDIACE\Cryptocurrency\Cryptocurrency-predicting.py", line 98, in checker_function
    df_main['future'] = df_main[f'{RATIO_TO_PRED}_close'].shift(-FUTURE_PRED_PERIOD)
  File "C:\Users\CORDIACE\Miniconda3\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\CORDIACE\Miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-USD_close'

**Comment by harsathAI** [comment]
This error is specific on your Pandas version. Try updating and run the script. Hope this helps
